version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: tigerracing
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: tigerracing
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  postgres_data:
